<RockSimDocument>
 <FileVersion>2</FileVersion>
 <DesignInformation>
  <RocketDesign>
   <Name>PK-56 Hi-Tech H45</Name>
   <CalculateCD>1</CalculateCD>
   <FixedCd>0.75</FixedCd>
   <FixedCd2>0.78</FixedCd2>
   <FixedCd3>0.8</FixedCd3>
   <StageCount>1</StageCount>
   <Stage3Mass>0.</Stage3Mass>
   <Stage2Mass>0.</Stage2Mass>
   <Stage1Mass>0.</Stage1Mass>
   <Stage321CG>0.</Stage321CG>
   <Stage32CG>0.</Stage32CG>
   <Stage3CG>0.</Stage3CG>
   <CPCalcFlags>5</CPCalcFlags>
   <LaunchGuideLength>914.40001207008</LaunchGuideLength>
   <UseKnownMass>0</UseKnownMass>
   <DefaultFinish>1</DefaultFinish>
   <FinishMedium>0</FinishMedium>
   <FinishCoatCount>2</FinishCoatCount>
   <GlueType>0</GlueType>
   <Comments></Comments>
   <Designer>LOC Precision</Designer>
   <CPSimFlags>4</CPSimFlags>
   <LastSerialNumber>111</LastSerialNumber>
   <DisplayFlags>1</DisplayFlags>
   <MetricsFlags>0</MetricsFlags>
   <CameraState></CameraState>
   <BarromanXN>0.,1021.51308815486,343.725683914181,0.</BarromanXN>
   <BarrowmanCNa>0.,16.568412242499,16.8976358889834,0.</BarrowmanCNa>
   <RockSimXN>0.,1059.37852967044,355.367999346391,0.</RockSimXN>
   <RockSimCNa>0.,23.6018155422747,25.1086068568132,0.</RockSimCNa>
   <ViewType>0</ViewType>
   <ViewStageCount>1</ViewStageCount>
   <ViewTypeEdit>0</ViewTypeEdit>
   <ViewStageCountEdit>0</ViewStageCountEdit>
   <ZoomFactor>0.</ZoomFactor>
   <ZoomFactorEdit>0.</ZoomFactorEdit>
   <ScrollPosX>0</ScrollPosX>
   <ScrollPosY>0</ScrollPosY>
   <ScrollPosXEdit>0</ScrollPosXEdit>
   <ScrollPosYEdit>0</ScrollPosYEdit>
   <ThreeDFlags>0</ThreeDFlags>
   <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
   <SimulationEventList>
    <SimulationEvent>
     <PartSerialNo>35</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>0</HasDeployed>
     <DeployedAt_Altitude>0.</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>0.</DeployedAt_Time>
     <DeviceID>-1</DeviceID>
    </SimulationEvent>
   </SimulationEventList>
   <Stage3Parts>
    <NoseCone>
     <PartMfg>LOC</PartMfg>
     <KnownMass>85.048569</KnownMass>
     <Density>1049.2093265</Density>
     <Material>Polystyrene PS</Material>
     <Name>Nose cone</Name>
     <KnownCG>147.574</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>149.04647635927</CalcMass>
     <CalcCG>185.543004859213</CalcCG>
     <WettedSurface>3.20124086195262e-002</WettedSurface>
     <PaintedSurface>3.20124086195262e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC</PartNo>
     <PartDesc>pnc-2.56</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>1</SerialNo>
     <DisplayFlags>0</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>2.</BarrowmanCNa>
     <BarrowmanXN>0.105955718910434</BarrowmanXN>
     <RockSimCNa>2.</RockSimCNa>
     <RockSimXN>0.105955718910434</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <Len>228.6</Len>
     <BaseDia>66.04</BaseDia>
     <FinishCode>1</FinishCode>
     <ShapeCode>1</ShapeCode>
     <ConstructionType>1</ConstructionType>
     <ShoulderLen>66.548</ShoulderLen>
     <WallThickness>3.175</WallThickness>
     <ShapeParameter>0.</ShapeParameter>
     <ShoulderOD>62.865</ShoulderOD>
     <PointList></PointList>
     <BaseExtensionLen>0.</BaseExtensionLen>
     <CoreDia>0.</CoreDia>
     <CoreLen>0.</CoreLen>
     <AttachedParts>
     </AttachedParts>
    </NoseCone>
    <BodyTube>
     <PartMfg>LOC/Precision</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>1121.29241</Density>
     <Material>Paper</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>52.4294511729156</CalcMass>
     <CalcCG>127.</CalcCG>
     <WettedSurface>5.3305626808017e-002</WettedSurface>
     <PaintedSurface>5.3305626808017e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC BT-2.56</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>2</SerialNo>
     <DisplayFlags>1</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>66.802</OD>
     <ID>65.024</ID>
     <Len>254.</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>0.</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>15.02524719</KnownMass>
       <Density>1121.29241</Density>
       <Material>Paper</Material>
       <Name>Tube coupler</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>-63.5</Xb>
       <CalcMass>25.5075846265147</CalcMass>
       <CalcCG>63.5</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>TC-2.56</PartNo>
       <PartDesc>Tube Coupler</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>3</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>65.024</OD>
       <ID>63.246</ID>
       <Len>127.</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>4</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>LOC/Precision</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>1121.29241</Density>
     <Material>Paper</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>157.288353518747</CalcMass>
     <CalcCG>381.</CalcCG>
     <WettedSurface>0.159916880424051</WettedSurface>
     <PaintedSurface>0.159916880424051</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC BT-2.56</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>4</SerialNo>
     <DisplayFlags>1</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>66.802</OD>
     <ID>65.024</ID>
     <Len>762.</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>0.</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Bulkhead</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>60.325</Xb>
       <CalcMass>7.64392411506657</CalcMass>
       <CalcCG>1.5875</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC BP-2.56</PartNo>
       <PartDesc>Bulkhead Plate</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>11</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>65.024</OD>
       <ID>0.</ID>
       <Len>3.175</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>1</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <MassObject>
       <PartMfg>DIY</PartMfg>
       <KnownMass>21.26214225</KnownMass>
       <Density>0.</Density>
       <Material></Material>
       <Name>Mass object</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>66.675</Xb>
       <CalcMass>0.</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>1/4-20 </PartNo>
       <PartDesc>Eye, whs, nut</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>12</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>0</TypeCode>
       <Len>0.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
      <BodyTube>
       <PartMfg>LOC/Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1121.29241</Density>
       <Material>Paper</Material>
       <Name>MMT</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-19.05</Xb>
       <CalcMass>50.1637138114656</CalcMass>
       <CalcCG>127.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC BT-1.52</PartNo>
       <PartDesc>Airframe tube</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>26</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>41.529</OD>
       <ID>38.735</ID>
       <Len>254.</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>1</IsMotorMount>
       <MotorDia>38.</MotorDia>
       <EngineOverhang>12.7</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>0</IsInsideTube>
       <AttachedParts>
       </AttachedParts>
      </BodyTube>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>9.525</Xb>
       <CalcMass>4.52595398529075</CalcMass>
       <CalcCG>1.5875</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC CR-2.56-1.52</PartNo>
       <PartDesc>Centering Ring</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>27</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>65.024</OD>
       <ID>41.529</ID>
       <Len>3.175</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>139.7</Xb>
       <CalcMass>4.52595398529075</CalcMass>
       <CalcCG>1.5875</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC CR-2.56-1.52</PartNo>
       <PartDesc>Centering Ring</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>31</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>65.024</OD>
       <ID>41.529</ID>
       <Len>3.175</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <CustomFinSet>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>337.5410523</Density>
       <Material>1/8 Aircraft Plywood</Material>
       <Name>Custom Fin set</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>622.3</Xb>
       <CalcMass>38.3526995855644</CalcMass>
       <CalcCG>67.2777184738536</CalcCG>
       <WettedSurface>2.06451205450312e-002</WettedSurface>
       <PaintedSurface>6.19353616350935e-002</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>FS-56</PartNo>
       <PartDesc>Fin set</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>32</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>14.568412242499</BarrowmanCNa>
       <BarrowmanXN>1.14720384346909</BarrowmanXN>
       <RockSimCNa>21.6018155422747</RockSimCNa>
       <RockSimXN>1.147651</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <FinCount>3</FinCount>
       <RootChord>127.</RootChord>
       <TipChord>72.13</TipChord>
       <SemiSpan>101.6</SemiSpan>
       <MidChordLen>102.045507617925</MidChordLen>
       <SweepDistance>36.96</SweepDistance>
       <Thickness>3.175</Thickness>
       <ShapeCode>2</ShapeCode>
       <FinishCode>1</FinishCode>
       <TipShapeCode>1</TipShapeCode>
       <TabLength>127.</TabLength>
       <TabDepth>12.6492</TabDepth>
       <TabOffset>0.</TabOffset>
       <SweepMode>0</SweepMode>
       <SweepAngle>0.</SweepAngle>
       <AverageChord>101.85</AverageChord>
       <EffectiveTipChord>72.1272707460728</EffectiveTipChord>
       <PointList>127.0000016764,0.|111.12500146685,101.60000134112|34.92500046101,101.60000134112|0.,0.</PointList>
       <AttachedParts>
       </AttachedParts>
      </CustomFinSet>
      <MassObject>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>7.08738075</KnownMass>
       <Density>1.02e-003</Density>
       <Material>1/16 In. braided nylon</Material>
       <Name>Shock cord mount</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>333.375</Xb>
       <CalcMass>0.310896</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>2</DensityType>
       <PartNo>SCM-2</PartNo>
       <PartDesc>Shock cord mount</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>33</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>1</TypeCode>
       <Len>304.8</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
      <MassObject>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>3.1251445372e-003</Density>
       <Material>1/2 In. flat elastic</Material>
       <Name>Shock cord</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>279.4</Xb>
       <CalcMass>8.57289649444704</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>2</DensityType>
       <PartNo>SC-500</PartNo>
       <PartDesc>1/2 In Elastic shock cord</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>34</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>1</TypeCode>
       <Len>2743.2</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
      <Parachute>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>28.349523</KnownMass>
       <Density>0.</Density>
       <Material>Rip stop nylon</Material>
       <Name>Parachute</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>123.825</Xb>
       <CalcMass>6.21792</CalcMass>
       <CalcCG>59.2666666666667</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LP-28</PartNo>
       <PartDesc>28 In. 8 lines</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>35</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <Dia>711.2</Dia>
       <SpillHoleDia>0.</SpillHoleDia>
       <SideCount>8</SideCount>
       <ShroudLineCount>8</ShroudLineCount>
       <Thickness>5.08e-002</Thickness>
       <ShroudLineLen>762.</ShroudLineLen>
       <ChuteCount>1</ChuteCount>
       <ShroudLineMassPerMM>1.02e-003</ShroudLineMassPerMM>
       <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
       <DragCoefficient>0.75</DragCoefficient>
       <AttachedParts>
       </AttachedParts>
      </Parachute>
      <LaunchLug>
       <PartMfg>LOC</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1121.29241</Density>
       <Material>Paper</Material>
       <Name>Launch lug</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>384.175</Xb>
       <CalcMass>1.02824068154975</CalcMass>
       <CalcCG>76.2</CalcCG>
       <WettedSurface>5.78248241378079e-003</WettedSurface>
       <PaintedSurface>3.04024487498196e-003</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC LL25</PartNo>
       <PartDesc>LL-25</PartDesc>
       <RadialLoc>36.576</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>36</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>6.35</OD>
       <ID>5.715</ID>
       <Len>152.4</Len>
       <FinishCode>1</FinishCode>
       <AttachedParts>
       </AttachedParts>
      </LaunchLug>
      <MassObject>
       <PartMfg>Custom</PartMfg>
       <KnownMass>93.5534259</KnownMass>
       <Density>0.</Density>
       <Material></Material>
       <Name><![CDATA[Paint & Glue]]></Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>304.8</Xb>
       <CalcMass>0.</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>51</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>0</TypeCode>
       <Len>0.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
     </AttachedParts>
    </BodyTube>
   </Stage3Parts>
   <Stage2Parts>
   </Stage2Parts>
   <Stage1Parts>
   </Stage1Parts>
  </RocketDesign>
 </DesignInformation>
 <SimulationResultsList>
  <SimulationResults>
   <MaxAltitude>204.133444512896</MaxAltitude>
   <MaxVelocity>64.7686496130586</MaxVelocity>
   <MaxAcceleration>78.4975241538008</MaxAcceleration>
   <TimeToApogee>6.63100000000055</TimeToApogee>
   <OptimalDelay>5.63100000000055</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>3.76012636065949,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>203.463796005142,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>6.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>7.00000000000067,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.</TimeToBurnout>
   <TimeToLanding>38.928</TimeToLanding>
   <TimeToEject>7.00000000000067</TimeToEject>
   <MinLaunchGuideLen>1.26010365319437</MinLaunchGuideLen>
   <MaxVertVelocity>64.7548578226236</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>78.4975241538008</MaxVertAcceleration>
   <MaxHorzAcceleration>0.113693367895861</MaxHorzAcceleration>
   <MaxRange>215.575889704443</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[F62T-6   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>11.4013166107721</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.91440001207008</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.644</TimeToWindShear>
   <TimeToFreeFlight>0.167</TimeToFreeFlight>
   <TimeToMaxVelocity>0.977000000000001</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.256</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>1.36125898858513</ExecutionTime>
   <RangeAtLanding>215.575889704443</RangeAtLanding>
   <VelocityAtLanding>7.20280190253777</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.37487940334574</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,7.00000000000067</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>35</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>203.463796005142</DeployedAt_Altitude>
     <DeployedAt_Velocity>3.76012636065949</DeployedAt_Velocity>
     <DeployedAt_Range>1.47949290472283</DeployedAt_Range>
     <DeployedAt_Time>7.00000000000067</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>F62T</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>26</MountSerialNo>
     <EjectionDelay>6.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>634.77192929197</MaxAltitude>
   <MaxVelocity>119.731511578008</MaxVelocity>
   <MaxAcceleration>87.6864534285482</MaxAcceleration>
   <TimeToApogee>10.6589999999995</TimeToApogee>
   <OptimalDelay>7.62799999999976</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>11.101712878747,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>632.288791624332,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>7.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>10.0309999999999,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>3.03099999999978</TimeToBurnout>
   <TimeToLanding>111.721000000169</TimeToLanding>
   <TimeToEject>10.0309999999999</TimeToEject>
   <MinLaunchGuideLen>1.06341709586536</MinLaunchGuideLen>
   <MaxVertVelocity>119.516776695841</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>87.6864534285482</MaxVertAcceleration>
   <MaxHorzAcceleration>11.7108950796195</MaxHorzAcceleration>
   <MaxRange>643.722949381052</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[G40-7   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>12.5326309560182</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.91440001207008</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.609</TimeToWindShear>
   <TimeToFreeFlight>0.15</TimeToFreeFlight>
   <TimeToMaxVelocity>2.47699999999984</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.e-002</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>8.46554166177777</ExecutionTime>
   <RangeAtLanding>643.722949381052</RangeAtLanding>
   <VelocityAtLanding>7.06253958384477</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.21596312194452</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,10.0309999999999</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>35</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>632.288791624332</DeployedAt_Altitude>
     <DeployedAt_Velocity>11.101712878747</DeployedAt_Velocity>
     <DeployedAt_Range>-33.6952145717629</DeployedAt_Range>
     <DeployedAt_Time>10.0309999999999</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>G40</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>A-WL</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>26</MountSerialNo>
     <EjectionDelay>7.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>615.164090061757</MaxAltitude>
   <MaxVelocity>146.381038275386</MaxVelocity>
   <MaxAcceleration>151.885972051469</MaxAcceleration>
   <TimeToApogee>9.23900000000032</TimeToApogee>
   <OptimalDelay>7.81800000000036</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>20.5235389418397,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>610.207324548829,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>7.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>8.42000000000077,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.42099999999995</TimeToBurnout>
   <TimeToLanding>107.497000000149</TimeToLanding>
   <TimeToEject>8.42000000000077</TimeToEject>
   <MinLaunchGuideLen>0.630629905063323</MinLaunchGuideLen>
   <MaxVertVelocity>146.300404039833</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>151.885972051469</MaxVertAcceleration>
   <MaxHorzAcceleration>12.4988012769959</MaxHorzAcceleration>
   <MaxRange>646.598779831099</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[G80-7   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>16.3359735529617</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.91440001207008</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.485</TimeToWindShear>
   <TimeToFreeFlight>0.136</TimeToFreeFlight>
   <TimeToMaxVelocity>1.36299999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>5.e-002</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>9.15481570257631</ExecutionTime>
   <RangeAtLanding>646.598779831099</RangeAtLanding>
   <VelocityAtLanding>7.04796156726208</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.1993946812252</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,8.42000000000077</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>35</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>610.207324548829</DeployedAt_Altitude>
     <DeployedAt_Velocity>20.5235389418397</DeployedAt_Velocity>
     <DeployedAt_Range>-13.2511543682872</DeployedAt_Range>
     <DeployedAt_Time>8.42000000000077</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>G80</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>A</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>26</MountSerialNo>
     <EjectionDelay>7.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>710.233372796125</MaxAltitude>
   <MaxVelocity>175.613100200865</MaxVelocity>
   <MaxAcceleration>378.259223177762</MaxAcceleration>
   <TimeToApogee>8.47100000000074</TimeToApogee>
   <OptimalDelay>6.9700000000008</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>41.5626603264311,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>701.755828787225,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>6.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>7.50000000000084,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.50099999999995</TimeToBurnout>
   <TimeToLanding>115.436000000187</TimeToLanding>
   <TimeToEject>7.50000000000084</TimeToEject>
   <MinLaunchGuideLen>0.566126302298185</MinLaunchGuideLen>
   <MaxVertVelocity>175.512970823621</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>192.265166359257</MaxVertAcceleration>
   <MaxHorzAcceleration>26.8512268591314</MaxHorzAcceleration>
   <MaxRange>700.732433867734</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H128W-6   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>17.7405961899814</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.91440001207008</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.472</TimeToWindShear>
   <TimeToFreeFlight>0.146</TimeToFreeFlight>
   <TimeToMaxVelocity>1.32699999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>7.50100000000084</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>11.1157361001693</ExecutionTime>
   <RangeAtLanding>700.732433867734</RangeAtLanding>
   <VelocityAtLanding>7.36666812209578</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.55946121118969</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,7.50000000000084</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>35</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>701.755828787225</DeployedAt_Altitude>
     <DeployedAt_Velocity>41.5626603264311</DeployedAt_Velocity>
     <DeployedAt_Range>-17.7675943638482</DeployedAt_Range>
     <DeployedAt_Time>7.50000000000084</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H128W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>26</MountSerialNo>
     <EjectionDelay>6.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>927.761691134433</MaxAltitude>
   <MaxVelocity>187.287034600915</MaxVelocity>
   <MaxAcceleration>434.237287091936</MaxAcceleration>
   <TimeToApogee>9.61900000000011</TimeToApogee>
   <OptimalDelay>7.01800000000028</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>46.5501765022505,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>918.208591720503,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>6.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>8.60000000000067,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>2.60099999999982</TimeToBurnout>
   <TimeToLanding>144.116000000324</TimeToLanding>
   <TimeToEject>8.60000000000067</TimeToEject>
   <MinLaunchGuideLen>0.643598841582264</MinLaunchGuideLen>
   <MaxVertVelocity>187.087197228815</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>150.775876989537</MaxVertAcceleration>
   <MaxHorzAcceleration>40.7159121615763</MaxHorzAcceleration>
   <MaxRange>867.376003523173</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H123W-6   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>16.1647854734141</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.91440001207008</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.474</TimeToWindShear>
   <TimeToFreeFlight>0.112</TimeToFreeFlight>
   <TimeToMaxVelocity>2.23299999999987</TimeToMaxVelocity>
   <TimeToMaxAcceleration>8.60100000000067</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>11.8536884627634</ExecutionTime>
   <RangeAtLanding>867.376003523173</RangeAtLanding>
   <VelocityAtLanding>7.55878867049052</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.77451240497321</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,8.60000000000067</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>35</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>918.208591720503</DeployedAt_Altitude>
     <DeployedAt_Velocity>46.5501765022505</DeployedAt_Velocity>
     <DeployedAt_Range>-35.4884551568743</DeployedAt_Range>
     <DeployedAt_Time>8.60000000000067</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H123W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>26</MountSerialNo>
     <EjectionDelay>6.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
 </SimulationResultsList>
</RockSimDocument>
